# Generated by Django 5.2.7 on 2025-11-07 02:22

from django.db import migrations, models


def migrate_azure_to_gemini(apps, schema_editor):
    """Update existing azure extraction methods to use gemini"""
    Document = apps.get_model('librarian', 'Document')
    Document.objects.filter(pdf_extraction_method='azure_read').update(
        pdf_extraction_method='gemini_read'
    )
    Document.objects.filter(pdf_extraction_method='azure_layout').update(
        pdf_extraction_method='gemini_layout'
    )


def reverse_migrate(apps, schema_editor):
    """Reverse migration - convert gemini back to azure"""
    Document = apps.get_model('librarian', 'Document')
    Document.objects.filter(pdf_extraction_method='gemini_read').update(
        pdf_extraction_method='azure_read'
    )
    Document.objects.filter(pdf_extraction_method='gemini_layout').update(
        pdf_extraction_method='azure_layout'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0006_remove_filename_from_savedfile'),
    ]

    operations = [
        migrations.RunPython(migrate_azure_to_gemini, reverse_migrate),
        migrations.AlterField(
            model_name='document',
            name='pdf_extraction_method',
            field=models.CharField(blank=True, choices=[('default', 'text only'), ('layout', 'text & layout'), ('gemini_read', 'OCR'), ('gemini_layout', 'OCR & layout')], max_length=40, null=True),
        ),
    ]
