# Generated by Django 5.2.7 on 2025-11-07 02:23

from django.db import migrations, models


def migrate_gpt_to_gemini(apps, schema_editor):
    """Update existing GPT model references to use Gemini"""
    ChatOptions = apps.get_model('chat', 'ChatOptions')

    # Map GPT models to Gemini equivalents
    gpt_to_gemini = {
        'gpt-5': 'gemini-2.0-flash',
        'gpt-4.1': 'gemini-1.5-pro',
        'gpt-4.1-mini': 'gemini-1.5-flash',
        'gpt-4.1-nano': 'gemini-1.5-flash',
        'gpt-4o': 'gemini-1.5-pro',
        'gpt-4o-mini': 'gemini-1.5-flash',
    }

    for gpt_model, gemini_model in gpt_to_gemini.items():
        ChatOptions.objects.filter(chat_model=gpt_model).update(chat_model=gemini_model)
        ChatOptions.objects.filter(qa_model=gpt_model).update(qa_model=gemini_model)
        ChatOptions.objects.filter(summarize_model=gpt_model).update(summarize_model=gemini_model)
        ChatOptions.objects.filter(translate_model=gpt_model).update(translate_model=gemini_model)


def reverse_migrate(apps, schema_editor):
    """Reverse migration - convert gemini back to gpt (best effort)"""
    ChatOptions = apps.get_model('chat', 'ChatOptions')

    # Map Gemini models to GPT equivalents (for rollback)
    gemini_to_gpt = {
        'gemini-2.0-flash': 'gpt-4.1-mini',
        'gemini-1.5-pro': 'gpt-4.1',
        'gemini-1.5-flash': 'gpt-4.1-mini',
    }

    for gemini_model, gpt_model in gemini_to_gpt.items():
        ChatOptions.objects.filter(chat_model=gemini_model).update(chat_model=gpt_model)
        ChatOptions.objects.filter(qa_model=gemini_model).update(qa_model=gpt_model)
        ChatOptions.objects.filter(summarize_model=gemini_model).update(summarize_model=gpt_model)
        ChatOptions.objects.filter(translate_model=gemini_model).update(translate_model=gpt_model)


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0026_migrate_azure_to_gemini_translation'),
    ]

    operations = [
        migrations.RunPython(migrate_gpt_to_gemini, reverse_migrate),
        migrations.AlterField(
            model_name='chatoptions',
            name='chat_model',
            field=models.CharField(default='gemini-1.5-flash', max_length=255),
        ),
        migrations.AlterField(
            model_name='chatoptions',
            name='qa_model',
            field=models.CharField(default='gemini-1.5-flash', max_length=255),
        ),
        migrations.AlterField(
            model_name='chatoptions',
            name='summarize_model',
            field=models.CharField(default='gemini-1.5-flash', max_length=255),
        ),
        migrations.AlterField(
            model_name='chatoptions',
            name='translate_model',
            field=models.CharField(default='gemini-1.5-flash', max_length=20),
        ),
    ]
